### PR TITLE
upgrade gatsby and add temporary instagram feed

### PR DESCRIPTION
**Pull request by lesliepassante**
# Why

Gatsby v2 is out, and it's much better, so seemed like a good time to upgrade. Also, Instagram!

# What

- Upgrades Gatsby and dependencies, and makes required changes to code
- Moves settings into `.env` files, to keep them more organized
- Adds `InstagramFeed` component to `index.js` page

### CODE REVIEW

**Comment by kuanluo** [comment]
@Victa to help with the design of Instagram feed, please. 🙏

**Comment by Victa** [comment]
@kuanluo do we want the feed like this? Maybe we need a title? but then it could compete with the username just above

- I am showing 3 images on Mobile
- 4 on tablet
- 6 for larger screens

cleanshot 2018-10-07 at 13 48 39 2x

**Comment by kuanluo** [comment]
Yay, instagram! A few thoughts: 

- I'd love a title "Follow up on Instagram" for the photos. 
- Moving the photos above `contact@` and the quote makes sense to me, which might involve a footer rethink as you mentioned, @Victa.

**Comment by Victa** [comment]
what do you think @kuanluo ?

cleanshot 2018-10-12 at 16 01 30 2x

**Comment by kuanluo** [comment]
Ooo!! Love !! Looks so good!! 👌

**Comment by lesliepassante** [comment]
👍

**Comment by Victa** [comment]
@lesliepassante merged so I can use the new template but not sure you looked at my comment above where I was looking for help!

https://github.com/nomadesign/ftw-retreat/pull/68/files/32bda5fb9621cbe7739c793eda700a80c0f9cd2e..3fc8604e459f226826ba62857367e2d91c5fc690#diff-11bff2e225aadef4861076de980e527e

Thanks!

**Pull request merged**
