### PR TITLE
add social tags

### PR DESCRIPTION
**Pull request by lesliepassante**
Adds more meta tags to the head, including `og` and `twitter` tags. Favicon images can be added in the same way.

### CODE REVIEW

**Comment by Victa** [comment]
@kuanluo should have a look at 
```
module.exports = {
  siteMetadata: {
    title: 'For the Women Retreat',
    description: 'A retreat for accomplished women in a beautiful environment.',
    keywords: 'retreat, women'
  },
  plugins: ['gatsby-plugin-react-helmet', 'gatsby-plugin-sass']
};
````

**Comment by Victa** [comment]
@kuanluo should have a look at 
```
module.exports = {
  siteMetadata: {
    title: 'For the Women Retreat',
    description: 'A retreat for accomplished women in a beautiful environment.',
    keywords: 'retreat, women'
  },
  plugins: ['gatsby-plugin-react-helmet', 'gatsby-plugin-sass']
};
````

**Comment by kuanluo** [comment]
`title` LGTM.
`description: A Beautiful Retreat for Creative Women. Five all-inclusive days of pliable time. Coming Fall 2018`
keywords: `women, retreat, creative, inclusive`

**Comment by Victa** [comment]
@lesliepassante ready to be merged!

**Pull request merged**
